/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCatalogueRouteImport } from './routes/_authenticated/catalogue'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedUtilisateursRouteImport } from './routes/_authenticated/utilisateurs'
import { Route as AuthenticatedChantiersIndexRouteImport } from './routes/_authenticated/chantiers.index'
import { Route as AuthenticatedFournisseurIndexRouteImport } from './routes/_authenticated/fournisseur.index'
import { Route as AuthenticatedFournisseurIdRouteImport } from './routes/_authenticated/fournisseur.$id'
import { Route as AuthenticatedChantiersIdIndexRouteImport } from './routes/_authenticated/chantiers.$id.index'
import { Route as AuthenticatedChantiersIdRecapMarcheIdRouteImport } from './routes/_authenticated/chantiers.$id.recap.$marcheId'
import { Route as AuthenticatedChantiersIdRemplirMarcheIdRouteImport } from './routes/_authenticated/chantiers.$id.remplir.$marcheId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogueRoute = AuthenticatedCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUtilisateursRoute =
  AuthenticatedUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChantiersIndexRoute =
  AuthenticatedChantiersIndexRouteImport.update({
    id: '/chantiers/',
    path: '/chantiers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFournisseurIndexRoute =
  AuthenticatedFournisseurIndexRouteImport.update({
    id: '/fournisseur/',
    path: '/fournisseur/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFournisseurIdRoute =
  AuthenticatedFournisseurIdRouteImport.update({
    id: '/fournisseur/$id',
    path: '/fournisseur/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChantiersIdIndexRoute =
  AuthenticatedChantiersIdIndexRouteImport.update({
    id: '/chantiers/$id/',
    path: '/chantiers/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChantiersIdRecapMarcheIdRoute =
  AuthenticatedChantiersIdRecapMarcheIdRouteImport.update({
    id: '/chantiers/$id/recap/$marcheId',
    path: '/chantiers/$id/recap/$marcheId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChantiersIdRemplirMarcheIdRoute =
  AuthenticatedChantiersIdRemplirMarcheIdRouteImport.update({
    id: '/chantiers/$id/remplir/$marcheId',
    path: '/chantiers/$id/remplir/$marcheId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/fournisseur/$id': typeof AuthenticatedFournisseurIdRoute
  '/chantiers/': typeof AuthenticatedChantiersIndexRoute
  '/fournisseur/': typeof AuthenticatedFournisseurIndexRoute
  '/chantiers/$id/': typeof AuthenticatedChantiersIdIndexRoute
  '/chantiers/$id/recap/$marcheId': typeof AuthenticatedChantiersIdRecapMarcheIdRoute
  '/chantiers/$id/remplir/$marcheId': typeof AuthenticatedChantiersIdRemplirMarcheIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/fournisseur/$id': typeof AuthenticatedFournisseurIdRoute
  '/chantiers': typeof AuthenticatedChantiersIndexRoute
  '/fournisseur': typeof AuthenticatedFournisseurIndexRoute
  '/chantiers/$id': typeof AuthenticatedChantiersIdIndexRoute
  '/chantiers/$id/recap/$marcheId': typeof AuthenticatedChantiersIdRecapMarcheIdRoute
  '/chantiers/$id/remplir/$marcheId': typeof AuthenticatedChantiersIdRemplirMarcheIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/catalogue': typeof AuthenticatedCatalogueRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/_authenticated/fournisseur/$id': typeof AuthenticatedFournisseurIdRoute
  '/_authenticated/chantiers/': typeof AuthenticatedChantiersIndexRoute
  '/_authenticated/fournisseur/': typeof AuthenticatedFournisseurIndexRoute
  '/_authenticated/chantiers/$id/': typeof AuthenticatedChantiersIdIndexRoute
  '/_authenticated/chantiers/$id/recap/$marcheId': typeof AuthenticatedChantiersIdRecapMarcheIdRoute
  '/_authenticated/chantiers/$id/remplir/$marcheId': typeof AuthenticatedChantiersIdRemplirMarcheIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalogue'
    | '/dashboard'
    | '/import'
    | '/journal'
    | '/parametres'
    | '/profil'
    | '/utilisateurs'
    | '/fournisseur/$id'
    | '/chantiers/'
    | '/fournisseur/'
    | '/chantiers/$id/'
    | '/chantiers/$id/recap/$marcheId'
    | '/chantiers/$id/remplir/$marcheId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalogue'
    | '/dashboard'
    | '/import'
    | '/journal'
    | '/parametres'
    | '/profil'
    | '/utilisateurs'
    | '/fournisseur/$id'
    | '/chantiers'
    | '/fournisseur'
    | '/chantiers/$id'
    | '/chantiers/$id/recap/$marcheId'
    | '/chantiers/$id/remplir/$marcheId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/catalogue'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/journal'
    | '/_authenticated/parametres'
    | '/_authenticated/profil'
    | '/_authenticated/utilisateurs'
    | '/_authenticated/fournisseur/$id'
    | '/_authenticated/chantiers/'
    | '/_authenticated/fournisseur/'
    | '/_authenticated/chantiers/$id/'
    | '/_authenticated/chantiers/$id/recap/$marcheId'
    | '/_authenticated/chantiers/$id/remplir/$marcheId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalogue': {
      id: '/_authenticated/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthenticatedCatalogueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/utilisateurs': {
      id: '/_authenticated/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthenticatedUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chantiers/': {
      id: '/_authenticated/chantiers/'
      path: '/chantiers'
      fullPath: '/chantiers/'
      preLoaderRoute: typeof AuthenticatedChantiersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseur/': {
      id: '/_authenticated/fournisseur/'
      path: '/fournisseur'
      fullPath: '/fournisseur/'
      preLoaderRoute: typeof AuthenticatedFournisseurIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseur/$id': {
      id: '/_authenticated/fournisseur/$id'
      path: '/fournisseur/$id'
      fullPath: '/fournisseur/$id'
      preLoaderRoute: typeof AuthenticatedFournisseurIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chantiers/$id/': {
      id: '/_authenticated/chantiers/$id/'
      path: '/chantiers/$id'
      fullPath: '/chantiers/$id/'
      preLoaderRoute: typeof AuthenticatedChantiersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chantiers/$id/recap/$marcheId': {
      id: '/_authenticated/chantiers/$id/recap/$marcheId'
      path: '/chantiers/$id/recap/$marcheId'
      fullPath: '/chantiers/$id/recap/$marcheId'
      preLoaderRoute: typeof AuthenticatedChantiersIdRecapMarcheIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chantiers/$id/remplir/$marcheId': {
      id: '/_authenticated/chantiers/$id/remplir/$marcheId'
      path: '/chantiers/$id/remplir/$marcheId'
      fullPath: '/chantiers/$id/remplir/$marcheId'
      preLoaderRoute: typeof AuthenticatedChantiersIdRemplirMarcheIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatalogueRoute: typeof AuthenticatedCatalogueRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedUtilisateursRoute: typeof AuthenticatedUtilisateursRoute
  AuthenticatedFournisseurIdRoute: typeof AuthenticatedFournisseurIdRoute
  AuthenticatedChantiersIndexRoute: typeof AuthenticatedChantiersIndexRoute
  AuthenticatedFournisseurIndexRoute: typeof AuthenticatedFournisseurIndexRoute
  AuthenticatedChantiersIdIndexRoute: typeof AuthenticatedChantiersIdIndexRoute
  AuthenticatedChantiersIdRecapMarcheIdRoute: typeof AuthenticatedChantiersIdRecapMarcheIdRoute
  AuthenticatedChantiersIdRemplirMarcheIdRoute: typeof AuthenticatedChantiersIdRemplirMarcheIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatalogueRoute: AuthenticatedCatalogueRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedUtilisateursRoute: AuthenticatedUtilisateursRoute,
  AuthenticatedFournisseurIdRoute: AuthenticatedFournisseurIdRoute,
  AuthenticatedChantiersIndexRoute: AuthenticatedChantiersIndexRoute,
  AuthenticatedFournisseurIndexRoute: AuthenticatedFournisseurIndexRoute,
  AuthenticatedChantiersIdIndexRoute: AuthenticatedChantiersIdIndexRoute,
  AuthenticatedChantiersIdRecapMarcheIdRoute:
    AuthenticatedChantiersIdRecapMarcheIdRoute,
  AuthenticatedChantiersIdRemplirMarcheIdRoute:
    AuthenticatedChantiersIdRemplirMarcheIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
